services:
    api:
        build: .
        ports:
            - "8000:8000"
        depends_on:
            db:
                condition: service_healthy
    db:
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_USER: myuser
            POSTGRES_PASSWORD: mypassword
            POSTGRES_DB: restaurants
        ports:
            - "5434:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U myuser -d restaurants"]
            interval: 5s
            retries: 5

volumes:
    postgres_data:
